
_G.AssetsTextureCfg = -- 贴图
{
    ["Currency"] = -- 通用
    {    
        {sName = "grass",   sPath = "Assets/Textures/grass.png"  },
        {sName = "tc",   sPath = "Assets/Textures/tc.png"  },
        {sName = "ball",   sPath = "Assets/Textures/ball.png"  },
        {sName = "hero_001",   sPath = "Assets/Textures/hero_001.png"  },
        {sName = "hero_002",   sPath = "Assets/Textures/hero_002.png"  },
        {sName = "hero_ani",   sPath = "Assets/Textures/hero_ani.png"  },
        {sName = "hero_ani_2",   sPath = "Assets/Textures/hero_ani_2.png"  },
        {sName = "hero_ani_3",   sPath = "Assets/Textures/hero_ani_3.png"  },
        {sName = "hero_ani_4",   sPath = "Assets/Textures/hero_ani_4.png"  },
        {sName = "hero_ani_5",   sPath = "Assets/Textures/hero_ani_5.png"  },
        {sName = "hero_ani_6",   sPath = "Assets/Textures/hero_ani_6.png"  },
        {sName = "blueanims",   sPath = "Assets/Textures/Can Pieces/blueanims.png"  },
        {sName = "blockercans",   sPath = "Assets/Textures/Can Pieces/blockercans.png"  },
        {sName = "rock1",   sPath = "Assets/Textures/rock1.png"  },
        {sName = "rock2",   sPath = "Assets/Textures/rock2.png"  },
        {sName = "rock3",   sPath = "Assets/Textures/rock3.png"  },
        {sName = "rock4",   sPath = "Assets/Textures/rock4.png"  },
        {sName = "flower1",   sPath = "Assets/Textures/flower1.png"  },
        {sName = "flower2",   sPath = "Assets/Textures/flower2.png"  },
        {sName = "flower3",   sPath = "Assets/Textures/flower3.png"  },
        {sName = "flower4",   sPath = "Assets/Textures/flower4.png"  },
        {sName = "born1",   sPath = "Assets/Textures/born1.png"  },
        {sName = "born2",   sPath = "Assets/Textures/born2.png"  },
        {sName = "born3",   sPath = "Assets/Textures/born3.png"  },
        {sName = "born4",   sPath = "Assets/Textures/born4.png"  },
        {sName = "ground1",   sPath = "Assets/Textures/ground1.png"  },
        {sName = "ground2",   sPath = "Assets/Textures/ground2.png"  },
        {sName = "001",   sPath = "Assets/Textures/001.png"  },
        {sName = "003",   sPath = "Assets/Textures/003.png"  },
        {sName = "008",   sPath = "Assets/Textures/008.png"  },
        {sName = "009",   sPath = "Assets/Textures/009.png"  },
        {sName = "012",   sPath = "Assets/Textures/012.png"  },
        
        {sName = "hero_1",   sPath = "Assets/Textures/hero_1.png"  },
        {sName = "tile_1",   sPath = "Assets/Textures/tile_1.png"  },
        {sName = "louti_1",   sPath = "Assets/Textures/louti_1.png"  },
    }, 
}